OpenConext/Stepup-Middleware

src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaCandidateRepository.php
This works around a Doctrine bug where it sees an entity as managed because it happens to reuse an object hash from an earlier created and destroyed object.
=> Remove the RaCandidates by using the EntityManager

src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaCandidateProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/projection.yml
An RA may choose to couple a new SF, this may not lead to a new candidacy.
@pmeulen do you agree with this solution?
=> Don't add RaCandidate if identity is already an RA

app/config/config.yml, src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Repository/RaLocationRepository.php
Note that the concept of a VettingLocation will have to go in the near future, as RaLocations and RegistrationAuthorityCredentials are clearly distinguishable concepts that do not need to be unified in this manner.
=> Fix vetting locations and email templates

src/Surfnet/StepupMiddleware/MiddlewareBundle/Service/EventStreamReplayer.php
I found out my event replays were consistently failing, because projection tables were not cleared automatically. This adds the tables to the EventStreamReplayer, causing them to be cleared properly before replaying.
=> Expand tables for event replays

app/DoctrineMigrations/Version20160728074605.php, app/config/config.yml, src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Entity/InstitutionConfigurationOptions.php, src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Projector/InstitutionConfigurationOptionsProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Repository/InstitutionConfigurationOptionsRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/ShowRaaContactInformationOptionType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/UseRaLocationsOptionType.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/projection.yml, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/ShowRaaContactInformationOptionTypeTest.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/UseRaLocationsOptionTypeTest.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Service/EventStreamReplayer.php
This adds the read side of the institution configuration options: repository, entity and projector.
=> Institution configuration options read-side

src/Surfnet/Stepup/Configuration/Value/UseRaLocationsOption.php, src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Entity/InstitutionConfigurationOptions.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/AuthorityRoleType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/CommonNameType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/ConfigurationContactInformationType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/ConfigurationInstitutionType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/ConfigurationLocationType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/ContactInformationType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/EmailType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/InstitutionType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/LocaleType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/LocationType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/NameIdType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/RaLocationNameType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/ShowRaaContactInformationOptionType.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/UseRaLocationsOptionType.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml, src/Surfnet/StepupMiddleware/ApiBundle/Service/InstitutionConfigurationOptionsService.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/ShowRaaContactInformationOptionTypeTest.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/UseRaLocationsOptionTypeTest.php, src/Surfnet/StepupMiddleware/ManagementBundle/Controller/InstitutionConfigurationController.php, src/Surfnet/StepupMiddleware/ManagementBundle/Resources/config/routing.yml, src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Controller/InstitutionConfigurationControllerTest.php
* Corrected boolean type conversion in custom Doctrine types
* Corrected exception messages for type conversion
* Corrected quoting in `ApiBundle/Resources/config/services.yml`
* Added action to show the options for all InstitutionConfigurations:
```
GET management/institution-configuration
[
{
"dev.organisation.example": {
"use_ra_locations": false,
"show_raa_contact_information": true
}
},
...
{
"yubi.organisation.example": {
"use_ra_locations": false,
"show_raa_contact_information": true
}
}
]
```
=> Show institution configuration options

src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Repository/InstitutionConfigurationOptionsRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/InstitutionConfigurationOptionsController.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/routing.yml
This depends on the service introduced in #146 
```
GET /institution-configuration-options/dev.organisation.example
{
"use_ra_locations": false,
"show_raa_contact_information": true
}
```
=> Add API for institution configuration options for institution

src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Entity/InstitutionConfigurationOptions.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/InstitutionConfigurationOptionsController.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Configuration/Entity/ConfiguredInstitutionTest.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Configuration/Entity/InstitutionConfigurationOptionsTest.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Configuration/Entity/RaLocationTest.php, src/Surfnet/StepupMiddleware/ManagementBundle/Controller/InstitutionConfigurationController.php
This PR:
* Changes the way InstitutionConfigurationOptions are serialized
* Adds tests for serialization of Configuration related Doctrine entitites (boyscout)
=> Correct JSON serialization for institution configuration

src/Surfnet/StepupMiddleware/ManagementBundle/Controller/InstitutionConfigurationController.php
This way, the results from the "GET" api can be used and altered when POSTing.
When we decided to use the JSON serialized variant for the InstitutionConfigurationOptions, we missed this.
=> Remove institution from show institution configuration options API

app/config/config.yml
Initial error report:
> ```sh
[root@test-app Stepup-Middleware-2.0.0-20160808152839Z-b38acd98a77c89bffa2649d956f92709954aa036]# php app/console cache:clear --env=prod --no-debug
Clearing the cache for the prod environment with debug false
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /opt/stepup/Stepup-Middleware-2.0.0-20160808152839Z-b38acd98a77c89bffa2649d956f92709954aa036/src/Surfnet/StepupMiddleware/ApiBundle/Tests/Configuration/Entity/ConfiguredInstitutionTest.php on line 26
[Symfony\Component\Debug\Exception\ClassNotFoundException] Attempted to load class "PHPUnit_Framework_TestCase" from the global namespace.  Did you forget a "use" statement?
```
What seems to happen is that the cache cannot be cleared due to Test classes being loaded during the `cache:clear` …
=> More specific configuration allows succesful cache:clear on prod

app/DoctrineMigrations/Version20160719090051.php
This ensures that this migration runs before a migration that depends on this migration being run.
Reported error:
```
migrating up to 20160728074605 from 20160607142244
…
++ migrating 20160719090052
Migration 20160719090052 failed during Execution. Error An exception occurred while executing 'INSERT INTO institution_configuration_options (institution, use_ra_locations_option, show_raa_contact_information_option) VALUES (?, ?, ?)' with params ["institution-a.nl", false, true]:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'middleware.institution_configuration_options' doesn't exist
```
Probable cause would be that after the creation of migration `20160719090052` the events as the result of commands triggered in that migration have been changed for other events, as well as the …
=> Change name of migration, influencing execution order

src/Surfnet/StepupMiddleware/CommandHandlingBundle/EventHandling/BufferedEventBus.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/event_sourcing.yml, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/EventHandling/BufferedEventBusTest.php
[132894351](https://www.pivotaltracker.com/story/show/132894351)
Doctrine uses PHP's [spl_object_hash](http://php.net/manual/en/function.spl-object-hash.php). Hashes can be re-assigned after a certain object has been destroyed / garbage collected.
It seems that we have reached an edge case wherein hash collisions occur during event replays. Similar edge cases have been reported at the [Doctrine repository](https://github.com/doctrine/doctrine2/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20spl_object_hash%20).
Clearing the entity manager after each event ensures the entity manager correctly inserts entities that have not been seen before.
This does come with the caveat that event listeners cannot hold references to entities crossing events.
=> Clear entity managers references after each event

src/Surfnet/Stepup/Identity/Identity.php, src/Surfnet/Stepup/Identity/Value/RegistrationAuthorityRole.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php
This PR makes it impossible for RAs to vet registrants outside of their institution, except for SRAAs.
This PR also enforces that only Identities with RA privileges can vet second factors.
This relates to SURFnet/Stepup-RA#133.
=> RAs should not be able to vet outside institution

src/Surfnet/Stepup/Identity/Identity.php, src/Surfnet/Stepup/Identity/Value/RegistrationAuthorityRole.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php
This reverts commit a1543deca6a1f989b12eca2c119644b3fa951a6a, reversing
changes made to 4b0c8a62ef1182754d887529d2f98ca4f20ae291.
In the Identity aggregate, it is not known whether a certain identity is an SRAA or not. If he is an SRAA, the registrationAuthority property is set to null -- contrary to what one might assume.
That is why these checks currently do not work.
In the future, we need to find another way to determine in the Identity aggregate whether the one doing the vetting is a registration authority and whether he is an SRAA.
See: https://www.pivotaltracker.com/story/show/135335407
Reverting this means that, in theory, any Identity can vet a second factor regardless of whether they are within the same institution.
However, these checks are already done by the front-ends: RA …
=> Revert RA-checking and cross-institution vetting check in Identity aggregate

README.md
[135688937](https://www.pivotaltracker.com/story/show/135688937)
Stepup repositories have been moved to the OpenConext organisation
=> Refer to new organisation

src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/MigrateInstitutionConfigurationsCommand.php
[135610963](https://www.pivotaltracker.com/story/show/135610963)
We need this in order to be able to case-insensitively deal with InstitutionConfigurationIds.
=> Introduce CLI for migrating institution configurations

src/Surfnet/Stepup/Configuration/Value/InstitutionConfigurationId.php, src/Surfnet/Stepup/Tests/Configuration/Value/InstitutionConfigurationIdTest.php
Normalizing the institution configuration id fixes issues when basing institutions on schachome-organizations that are expected to work case-insensitively
The original construction of the (unnormalized) institution configuration id will be deprecated in favor of using normalized institution configuration ids
=> Introduce normalized institution configuration id

src/Surfnet/Stepup/Configuration/InstitutionConfiguration.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/CommandHandler/InstitutionConfigurationCommandHandler.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Configuration/CommandHandler/InstitutionConfigurationCommandHandlerTest.php
[135610963](https://www.pivotaltracker.com/story/show/135610963)
In this PR, the institution configuration command handler is updated to deal with both normalized and unnormalized InstitutionConfigurationIds. Until a migration has done to use only normalized InstitutionConfigurationIds, we have to offer fallbacks for the old, deprecated method.
=> Update command handler for dealing with both normalized and unnormalized InstitutionConfigurationIds

app/config/config_dev_event_replay.yml, app/config/config_prod_event_replay.yml, src/Surfnet/Stepup/Configuration/InstitutionConfiguration.php, src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Projector/RaLocationProjector.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/Command/RemoveInstitutionConfigurationByUnnormalizedIdCommand.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Pipeline/AuthorizingStage.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/MigrateInstitutionConfigurationsCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Migrations/InstitutionConfiguration/InstitutionConfigurationState.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Migrations/InstitutionConfiguration/MappedInstitutionConfiguration.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/services.yml, src/Surfnet/StepupMiddleware/MiddlewareBundle/SurfnetStepupMiddlewareMiddlewareBundle.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Tests/Migrations/InstitutionConfiguration/MappedInstitutionConfigurationTest.php
[135610963](https://www.pivotaltracker.com/story/show/135610963)
The InstitutionConfigurations are migrated in order to update existing InstitutionConfigurationIds to be handled case-insensitively.
=> Implement InstitutionConfiguration migration

src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/ReplaySpecificEventsCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/SurfnetStepupMiddlewareMiddlewareBundle.php
This new command is based on the ReplayEventsCommand that runs a replayer for all events, which was primarily used for development purposes.
Its purpose is to replay specific events for specific projectors.
=> Introduce specific event replay command

src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/ReplaySpecificEventsCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/EventSourcing/EventCollection.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/event_replaying.yml, src/Surfnet/StepupMiddleware/MiddlewareBundle/Tests/EventSourcing/EventCollectionTest.php
The selection can be a bit tedious, as Symfony Console requires you to select them by number.
It looks like this in the command line:
```
$ app/console stepup:event:replay
Which events would you like to replay? Please supply a comma-separated list of numbers.
[0 ] Surfnet\Stepup\Configuration\Event\AllowedSecondFactorListUpdatedEvent
[1 ] Surfnet\Stepup\Configuration\Event\ConfigurationUpdatedEvent
[2 ] Surfnet\Stepup\Configuration\Event\EmailTemplatesUpdatedEvent
[3 ] Surfnet\Stepup\Configuration\Event\IdentityProvidersUpdatedEvent
[4 ] Surfnet\Stepup\Configuration\Event\InstitutionConfigurationRemovedEvent
[5 ] Surfnet\Stepup\Configuration\Event\NewConfigurationCreatedEvent
[6 ] …
```
=> Feature/specific replay/event selection

app/DoctrineMigrations/Version20170216085513.php, src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Entity/AllowedSecondFactor.php
This corrects the primary key to be a compound key: the combination of
institution allowed second factor type is unique, but each institution
can have multiple second factor types. Since a PK also enforces a unique
constraint, having a PK on institution (a value object) limits the
allowed second factors to one per institution. By correcting the PK to
span both columns (Identity first for performance considerations), this
artificial limit is removed.
=> Multiple AllowedSecondFactors for the same institution can be saved

src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/ReconfigureInstitutionRequestValidatorTest.php, src/Surfnet/StepupMiddleware/ManagementBundle/Validator/ReconfigureInstitutionRequestValidator.php
The database is collated in a case-insensitive manner. As far as the database is concerned "Institution-a" == "institution-a".
This is why, when replacing an institution on the whitelist with the same institution name but with different casing,
the configured_institution is not changed: the InstitutionConfigurationProcessor detects no changes.
That is how you can have different casing as a configured_institution and as a whitelist_entry.
This goes wrong when trying to validate an institution configuration command as we check whether or not the
institution to configure is actually listed as a configured_institution.
This check was case-sensitive while its behavior should mirror the database, which works case-insensitive.
=> Validate institution names case-insensitively

docs/MiddlewareConfiguration.md, src/Surfnet/StepupMiddleware/ManagementBundle/Validator/IdentityProviderConfigurationValidator.php, src/Surfnet/StepupMiddleware/ManagementBundle/Validator/ServiceProviderConfigurationValidator.php
The flag 'use_pdp' can be omitted and defaults to false.
=> Add a 'use PDP' flag to IdP/Sp configuration

app/DoctrineMigrations/Version20171113123232.php, src/Surfnet/Stepup/DateTime/DateTime.php, src/Surfnet/Stepup/Identity/Entity/VerifiedSecondFactor.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/VerifiedSecondFactor.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/SecondFactorProjector.php
This change is required for RA to show expiration errors when looking
up verified registration codes.
See: https://www.pivotaltracker.com/story/show/133928873
=> Remember registration request date in verified SF projections

app/config/parameters.yml.dist, src/Surfnet/Stepup/Identity/Api/Identity.php, src/Surfnet/Stepup/Identity/Identity.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/IdentityCommandHandler.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/command_handlers.yml, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/SecondFactorRevocationTest.php
**Review notes**
A config parameter can be set to indicate the maximum number of tokens
allowed for each identity. The IdentityCommandHandler sets this value
on the identity instance. This in turn allows the identity instance to
validate whether or not the requested additional token is allowed or
not.
A sensible default was set in the parameters.yml.dist file.
**Tasks**
This PR is part of a series of changes in [SS](https://github.com/OpenConext/Stepup-SelfService/pull/127), [MW](https://github.com/OpenConext/Stepup-Middleware/pull/199) and [GW](https://github.com/OpenConext/Stepup-Gateway/pull/123).
For more information about the changes see [Pivotal](https://www.pivotaltracker.com/story/show/144697285) and the updated [docs](https://github.com/OpenConext/Stepup-Deploy/wiki/API-Design).
=> Allow registration of multiple tokens

src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/Command/ReconfigureInstitutionConfigurationOptionsCommand.php
**More information**
See commit message for detailed information about the bugfix
**Test instructions**
This can be tested by running the `/management/institution-configuration` api call (can be called from postman). 
I've tested with the following body:
```
{
"dev.organisation.example": {
"use_ra_locations": true, 
"show_raa_contact_information": true,
"allowed_second_factors": ["yubikey", "tiqr", "non-existing-token"]
}
}
```
This no longer returns the Symfony 500 error but shows a nicer application error message:
```
{
"errors": [
"Institution(dev.organisation.example): Option \"allowed_second_factors\" for \"non-existing-token\" must contain valid second factor types"
]
}
```
=> Do not validate SecondFactorTypes in Command

composer.json, composer.lock, src/Surfnet/Stepup/Identity/Value/SecondFactorIdentifierFactory.php
This PR adresses the problem described in this [pivotal bug](https://www.pivotaltracker.com/story/show/153250034) The 'proposed' solution of injecting the SFTypeService was dropped in favor of a more pragmatic solution. 
In this solution I assume the SF Type is GSSF if none of the other types are valid. This might pass along an invalid Gssf type but this will be checked later on in the code.
=> Stop using the isGssf method on SecondFactorType

app/config/security.yml
The firewall security config is changed slightly. The monitor entry was
moved one level up to prevent it from being affected by the api entry.
In effect this change ensures the api authentication mechanism is not
triggered on the health and info endpoint.
=> Move monitor entry up in firewall config

.gitignore, app/Resources/translations/messages.en_GB.xliff, app/Resources/translations/messages.nl_NL.xliff, bin/extract-translations.sh, composer.json, composer.lock
The previous version of the JMS translation bundle (1.1) did not
support PHP 5.6 which we now require because of the recent changes in
the stepup SAML bundle. This commit updates the translation bundle to
version 1.3, fixing the broken translation:extract command.
The XLIFF files are regenerated because the data in these files are
slightly changed in version 1.3.
=> Update translation bundle to new version

src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_configuration/invalid_sp_loa_uppercase_institution_sho.php, src/Surfnet/StepupMiddleware/ManagementBundle/Validator/ServiceProviderConfigurationValidator.php
The institution identifier (matching the SHO for authenticating users)
must be set as lower case values. This is validated in the assertion
method that was added to the ServiceProviderConfigurationValidator.
=> Add validation on institution SHO

app/DoctrineMigrations/Version20180131150800.php, src/Surfnet/StepupMiddleware/GatewayBundle/Entity/SecondFactor.php
In a not so recent change the second factor entity diverged from its
Gateway counterpart. The Gateway and Middleware schema definition of
this entity should be identical.
Change was introduced in migration: Version20141210174213
=> Reintroduce the index on second_factors name_id

src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Command/ProveGssfPossessionCommand.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/IdentityCommandHandler.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php
Now that GSSP tokens can be configured by config, any assumption in the
code that Tiqr is the only GSSP must be revised. This commit does just
that for the IdentityCommandHandler.
In addition the ProveGssfPossessionCommand has been updated with a
correction on the Phpdoc of the $stepupProvider field.
=> Stop assuming Tiqr is the only GSSP

app/DoctrineMigrations/Version20180330094402.php, src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Entity/InstitutionConfigurationOptions.php
While not intended, email verification was disabled for existing
institutions after upgrading to 2.7.0. Enabling email verification
for those institutions was tricky because the user first has to
'disable' it before it could be enabled again.
This commit fixes the problem by defaulting the column to true,
matching the expectation of underlying code.
=> Require email verification by default

src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaCandidateProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaCandidateRepository.php
Vetting a second second factor token triggered an error because the
'ra_candidate' projection assumed a RA can never have more than one
token. Instead of inserting the ra_candidate, we merge it with a
potential existing ra_candidate entry.
=> Allow RA's to register multiple second factor tokens

src/Surfnet/StepupMiddleware/CommandHandlingBundle/DependencyInjection/SurfnetStepupMiddlewareCommandHandlingExtension.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/EmailVerificationMailService.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/RegistrationMailService.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/SecondFactorRevocationMailService.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/SecondFactorVettedMailService.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/processors.yml
**Change description**
The `selfServiceUrl` has been made available in the following templates:
* vetted (SecondFactorVettedMailService)
* registration_code_with_ras (RegistrationMailService)
* registration_code_with_ra_locations (RegistrationMailService)
* confirm_email (EmailVerificationMailService)
**Test instructions**
Post updated `management/configuration` to the middleware API. The mail templates can now all hold the `{{ selfServiceUrl }}` translation parameter.
- The `confirm_email` mail template is sent when the user is presented with the mail confirmation challenge.
- `registration_code_with_ras` / `registration_code_with_ra_locations` is sent at the end of the registration process in SelfService.
- The `vetted` template will be sent after successfull registration at RA. (I was …
=> Make selfServiceUrl available in mail templates

src/Surfnet/Stepup/Identity/Event/EmailVerifiedEvent.php, src/Surfnet/Stepup/Identity/Event/GssfPossessionProvenAndVerifiedEvent.php, src/Surfnet/Stepup/Identity/Event/PhonePossessionProvenAndVerifiedEvent.php, src/Surfnet/Stepup/Identity/Event/PossessionProvenAndVerified.php, src/Surfnet/Stepup/Identity/Event/U2fDevicePossessionProvenAndVerifiedEvent.php, src/Surfnet/Stepup/Identity/Event/YubikeyPossessionProvenAndVerifiedEvent.php, src/Surfnet/Stepup/Identity/Identity.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Processor/RegistrationEmailProcessor.php
PR #221 broke the registration confirmation email for institutions
with email verification disabled. Stepup now always sends the
confirmation email regardless of the email verification setting.
=> Always send registration confirmation email

docs/personal-data.md
Description of the personal data stored in middleware. The introduction is in the Stepup-Deploy wiki: https://github.com/OpenConext/Stepup-Deploy/wiki/Personal-Data 
My plan is to store the description with the individual components. That should help keeping the description up to date.
Document should be useful as input for GDPR audit, and for design discussions for deprovisioning
=> Describe personal data stored in Stepup-Middleware

src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Service/InstitutionConfigurationOptionsService.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Configuration/Service/InstitutionConfigurationOptionsServiceTest.php
Fix an error when the institution configuration is
null. So now the code could handle institutions
without institution configuration options.
https://www.pivotaltracker.com/n/projects/1163646/stories/159491443
=> Fix SRAA command for institution without config

CHANGELOG.md
When the 'testcookie' is set, Nginx and PHP-fpm will set the APP_DEV
environment variable to 'test'.
If the variable for some reason is not set, the system falls back on the
default 'dev' environment.
See https://www.pivotaltracker.com/story/show/156570267
=> Set Symfony environment from cookie if available

app/config/parameters.yml.dist, app_dev.php.dist, app_test.php.dist
Without it, a PHP fatal error is being raised during runtime:
Uncaught Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException: The parameter "trusted_proxies" must be defined.
=> Add missing trusted_proxies-setting

src/Surfnet/StepupMiddleware/ApiBundle/Controller/AuditLogController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/CommandController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/IdentityController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/InstitutionConfigurationOptionsController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/InstitutionListingController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaCandidateController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaListingController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaLocationController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaSecondFactorController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/SraaController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/UnverifiedSecondFactorController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/VerifiedSecondFactorController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/VettedSecondFactorController.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml, src/Surfnet/StepupMiddleware/ManagementBundle/Controller/ConfigurationController.php, src/Surfnet/StepupMiddleware/ManagementBundle/Controller/InstitutionConfigurationController.php, src/Surfnet/StepupMiddleware/ManagementBundle/Controller/RightToBeForgottenController.php, src/Surfnet/StepupMiddleware/ManagementBundle/Controller/WhitelistController.php, src/Surfnet/StepupMiddleware/ManagementBundle/Resources/config/services.yml
The controller services are autowired.
The previously used getters, who where retrieving the dependencies using
the service container, have been substituted by private fields that are
populated at construction time.
See: https://www.pivotaltracker.com/story/show/160546671
Task: "Chore: Make ApiBundle controllers services and utilize DI"
=> Use DI in managment bundle controllers

docs/MiddlewareAPI.md, src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Repository/AuthorizationRepositoryFactory.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/IdentityController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaSecondFactorController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/VerifiedSecondFactorController.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/IdentityQuery.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/RaSecondFactorQuery.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/VerifiedSecondFactorQuery.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/IdentityRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaSecondFactorRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/VerifiedSecondFactorRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/IdentityService.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml
The main purpose of this PR is to add middleware endpoints used in RA to start a vetting procedure.
Also a bit of boyscouting was done to prevent coupling to allow changes in the authcontext logic much easier later on. Therefore the authorization context was added to the query in the controller. Also a special factory is added to set a AuthorizationFilter by DI to the repositories which needed filtering based on the authorization context to prevent coupling of the filter with the services.
This PR also removed the AuthContextFactory from the identity endpoint. 
See: https://www.pivotaltracker.com/story/show/160283514
=> Update vetting procedure endpoints

app/config/events.yml
In #246 we saw the addition of:
- Surfnet\Stepup\Identity\Event\IdentityAccreditedAsRaForInstitutionEvent
- Surfnet\Stepup\Identity\Event\IdentityAccreditedAsRaaForInstitutionEvent
- Surfnet\Stepup\Identity\Event\AppointedAsRaForInstitutionEvent
- Surfnet\Stepup\Identity\Event\AppointedAsRaaForInstitutionEvent
- Surfnet\Stepup\Identity\Event\RegistrationAuthorityInformationAmendedForInstitutionEvent
- Surfnet\Stepup\Identity\Event\RegistrationAuthorityRetractedForInstitutionEvent
These events needed to be registered in the events.yml to be able to use
them in the middleware. To build aggregates and perform event replays.
See: https://github.com/OpenConext/Stepup-Middleware/pull/246
=> Register new events in events.yml

src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/AuditLogEntry.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/AuditLogRepository.php
The previously added events where not yet projected in the event log.
This change registers the relevant events on the AuditLogEntry entity
and the AuditLogRepository. Enabling the new events for display.
What is not yet in this PR is the actual RA institution you have been appointed RA(A) privileges for. This feature is discussed in this Pivotal issue in the comment section: https://www.pivotaltracker.com/story/show/160283522/comments/195972803
=> Display the new events in auditlog

app/DoctrineMigrations/Version20181101103348.php, src/Surfnet/Stepup/Identity/AuditLog/Metadata.php, src/Surfnet/Stepup/Identity/Event/AppointedAsRaForInstitutionEvent.php, src/Surfnet/Stepup/Identity/Event/AppointedAsRaaForInstitutionEvent.php, src/Surfnet/Stepup/Identity/Event/IdentityAccreditedAsRaForInstitutionEvent.php, src/Surfnet/Stepup/Identity/Event/IdentityAccreditedAsRaaForInstitutionEvent.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/AuditLogEntry.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/AuditLogProjector.php
The RA institution is saved to the auditlog projection when it is set on the metadata context.
This resulted in a small schema change. So run the migration!
Think/discuss: do we need to facilitate additional support for the previous versions of these events?
See: https://github.com/OpenConext/Stepup-RA/pull/181
See: https://github.com/OpenConext/Stepup-Middleware-clientbundle/pull/71
See: https://github.com/OpenConext/Stepup-Middleware/pull/253
=>  Allow storing of the ra institution in audit log

src/Surfnet/Stepup/Configuration/InstitutionConfiguration.php, src/Surfnet/Stepup/Configuration/Value/InstitutionAuthorizationOption.php, src/Surfnet/Stepup/Identity/Identity.php, src/Surfnet/Stepup/Tests/Configuration/Value/InstitutionAuthorizationOptionTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/RegistrationAuthorityCommandHandler.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/RegistrationAuthorityCommandHandlerTest.php
The check for appointing roles in the identity aggregate was
incorrect. This change will fix this behavior.
=> Fix the select_raa check when appointing roles

docs/MiddlewareAPI.md, src/Surfnet/Stepup/Identity/Event/IdentityAccreditedAsRaaEvent.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/IdentityController.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/IdentityRepository.php
In order to ensure we can find an identity, we no longer need to set
the institution of that identity. As the RA(A) might be RA for an
institution it does not have a SHO for.
This change was applied in:
- https://github.com/OpenConext/Stepup-RA/pull/183
- https://github.com/OpenConext/Stepup-SelfService/pull/161
- Middleware-clientbundle https://github.com/OpenConext/Stepup-Middleware-clientbundle/pull/72
=> Make institution parameter optional

src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Filter/InstitutionAuthorizationRepositoryFilter.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Filter/InstitutionAuthorizationRepositoryFilterTest.php
There was a bug in the authorization filter which filtered out
the ra's which could act on behalf of another institution.
=> Fix ra-authorization filter

src/Surfnet/Stepup/Configuration/Event/SelectRaaOptionChangedEvent.php, src/Surfnet/Stepup/Identity/Entity/InstitutionCollection.php, src/Surfnet/Stepup/Identity/Identity.php, src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Filter/InstitutionAuthorizationRepositoryFilter.php, src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Service/InstitutionAuthorizationService.php, src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Value/InstitutionAuthorizationContext.php, src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Value/InstitutionAuthorizationContextInterface.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaSecondFactorController.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaCandidateProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/IdentityRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/InstitutionListingRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaCandidateRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaListingRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaSecondFactorRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/VerifiedSecondFactorRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/RaCandidateService.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/RaListingService.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/projection.yml, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Filter/InstitutionAuthorizationRepositoryFilterTest.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Service/InstitutionAuthorizationServiceTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/RegistrationAuthorityCommandHandler.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/RegistrationAuthorityCommandHandlerTest.php
In the filtering based on the authorization, there is a bug which prevents fetching the correct RA candidates and RAs themselves.
The problem was that initially the flattened ra_lsiting and ra_candidate listings didn't store an identity in combination with a ra_institution and joined the identity based on the institution configuration. We later decided to flatten the projections and store those entries with both identity and raInstitution. Therefore the join wasn't valid anymore and should have been removed.
Also, there seemed to be a problem with the reuse of the ra_lising projections to determine authorizations based on the view which should be fixed later on by for example introduce a new endpoint in MW for authorizations. This to prevent breaking things when changing unrelated logic. …
=> Fix authorization filter

src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Filter/InstitutionAuthorizationRepositoryFilter.php, src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Service/InstitutionAuthorizationService.php, src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Value/InstitutionAuthorizationContext.php, src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Value/InstitutionAuthorizationContextInterface.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/IdentityController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaCandidateController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaListingController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaSecondFactorController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/VerifiedSecondFactorController.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/IdentityQuery.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/RaCandidateQuery.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/RaListingQuery.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/RaSecondFactorQuery.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/VerifiedSecondFactorQuery.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/InstitutionListingRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaCandidateRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaListingRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/RaCandidateService.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Filter/InstitutionAuthorizationRepositoryFilterTest.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Service/InstitutionAuthorizationServiceTest.php
Because the Raa switcher was removed we needed the actorId to
check if the actor is allowed to update RAA's from a given institution
or to determine if an actor is an SRAA.
=> Add actorId to management

src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaListingRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Value/RegistrationAuthorityCredentials.php
After the fix to be able to login with the highest ra(a) level the
original static method was removed, but this shouldn't be removed.
Restored the original method to allow construction of ra-listings.
=> Fix ra-listing static factory method

src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Service/InstitutionAuthorizationService.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/ProfileController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaSecondFactorController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/VerifiedSecondFactorController.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/InstitutionListingRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/ProfileService.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Value/AuthorizedInstitutionCollection.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Service/InstitutionAuthorizationServiceTest.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Identity/Value/AuthorizedInstitutionCollectionTest.php
By including the implicit roles on the profile page, the user can see for which institutions he/she can perform RA(A) tasks.
This PR might be a little rough around the edges. @pablothedude feel free to rework this PR. I would also greatly appreciate your feedback on my solution. Your proposal did not seem to cut the bill fully, but I might have misunderstood some of your intentions.
This is in support of https://www.pivotaltracker.com/story/show/164244620 (task 2)
And behat test coverage is found in: https://github.com/OpenConext/Stepup-Deploy/pull/83
=> Include implicit roles on the profile endpoint

src/Surfnet/StepupMiddleware/ApiBundle/Controller/VerifiedSecondFactorController.php
RA's are able to vet second factor tokens, in order to be able
to find the verified second factor, the RA searches for the token by
activation code. Before this fix, the RA would not find the token as the
controller was configured to require the RAA role in order to find a
token.
https://www.pivotaltracker.com/story/show/164398880
=> Ensure RA filter applied when searching verified second factor

src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaSecondFactorController.php
The authorization level was set to RAA while RA should be already valid.
=> Fix ra second factor auth level

composer.lock
To harden against:
CVE-2019-10912: Prevent destructors with side-effects from being unserialized
=> Update Symfony PHPUnit bridge

app/config/config.yml
The implicit __toString call is no longer allowed, and a critical error is raised by Twig. The solution is to add the __toString calls to the list of allowed sandbox methods.
This change fixes the problem where sending the verification mail message would trigger an error.
=> Add additional allowed sandbox methods

docs/MiddlewareAPI.md, src/Surfnet/StepupMiddleware/ApiBundle/Controller/VerifiedSecondFactorController.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/VerifiedSecondFactorOfIdentityQuery.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/VerifiedSecondFactorRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/SecondFactorService.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/routing.yml
This endpoint does not apply the FGA authz filtering. Allowing the self
service user to see all it's tokens regardless of institution
=> Add Self Service verified SF collection endpoint

src/Surfnet/StepupMiddleware/ApiBundle/Controller/CommandController.php
In order to clarify the reason why a RA which institution isn't on the
whitelist isn't allowed this exception is added. Before this resulted
in an exception thrown when trying to access a method on a null object.
`Error: Call to a member function isSraa() on null`
=> Add exception for not whitelisted RA's

app/config/config.yml
When testing SS registration the process failed because the mail
templates were using __toString methods from value objects while
the specific class methods weren't whitelisted for twig.
This was started in:
https://github.com/OpenConext/Stepup-Middleware/pull/276
https://www.pivotaltracker.com/story/show/166204879
=> Whitelist missing toString methods

.travis.yml, src/Surfnet/Stepup/Identity/Entity/VettedSecondFactor.php, src/Surfnet/Stepup/Identity/Event/VettedSecondFactorsAllRevokedEvent.php, src/Surfnet/Stepup/Identity/Identity.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaCandidateProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaCandidateRepository.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/SecondFactorRevocationTest.php
When a token gets removed the identity also gets removed from the
ra candidate projection. This also occurs when a identity still
has valid tokens left.
This fix will make sure that a candidate only is removed when his last
token gets removed.
=> Fix RA removal when token gets removed

CHANGELOG.md, composer.lock
This change will apply the countermeasures to harden against
CVE 2019-3465 and will effectively bump `robrichards/xmlseclibs` to
version 3.0.4
This release is targetted at the R17 (3.0.x) code wich currently resides on develop/master
=> Upgrade Stepup-saml-bundle to version 4.1.8

app/DoctrineMigrations/Version20200114161618.php, src/Surfnet/Stepup/Configuration/Value/Institution.php, src/Surfnet/Stepup/Identity/Value/Institution.php, src/Surfnet/Stepup/Tests/Configuration/Value/InstitutionConfigurationIdTest.php, src/Surfnet/Stepup/Tests/Configuration/Value/InstitutionTest.php, src/Surfnet/Stepup/Tests/Identity/Value/InstitutionTest.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/ConfigurationInstitutionTypeTest.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/InstitutionTypeTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Configuration/Processor/InstitutionConfigurationProcessorTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/WhitelistCommandHandlerTest.php
The domain accepted mixed casing sho's. This shouldn't be possible.
Therefore this is now enforced in the domain itself and a migration
is added to convert all occurrences to lowercase.
=> Fix sho mixed casing once and for all

app/DoctrineMigrations/Version20200114161618.php
Some fields were missed when the institutions were lowercased. This was
because sometimes a VO was used and sometimes a string.
=> Add some missing institution fields to migration

src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Service/CommandAuthorizationService.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Service/CommandAuthorizationServiceTest.php
After the authorization was offloaded to a dedicated service
only RA commands were allowed by an RAA and not a RA. This
resulted in RA's not being able to execute commands in the RA
while they should.
A test was added in deploy to test this fix.
https://github.com/OpenConext/Stepup-Deploy/pull/97
=> Allow RA commands in RA environment

CHANGELOG.md, src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Service/CommandAuthorizationService.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Service/CommandAuthorizationServiceTest.php
The MW command authorization service did pass this command as a valid self service command, but did not pass the successive RA check.
https://www.pivotaltracker.com/story/show/171325732
=> Allow language switching from SelfService

src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaCandidateRepository.php
The ra-candidate search form allows filtering search results on
institution. But that filter select list was empty. Because the
institutions where not added to the search results.
That is fixed in the RaCandidateRepository::createOptionsQuery method by
also selecting the institutions.
https://www.pivotaltracker.com/story/show/171512620
=> Add missing institution to the filter options

src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaCandidateRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaListingRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaSecondFactorRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/VerifiedSecondFactorRepository.php
The RA-Candidates were filtered on RA institution but that should have
been on institution. Because we only want to use identities from the
institutions we are currently RA for.
=> Fix invalid RA candidate authorization

src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Repository/InstitutionAuthorizationRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaCandidateProjector.php
When retracting an RA role the identity should have been added to the
candidate projection. This however didn't work as intended and the user
was reverted to his own institution and not the ra-institution.
A test was added in deploy to reproduce and mitigate the bug.
https://github.com/OpenConext/Stepup-Deploy/pull/101/commits/2e5e5bee32014c292a2af8e5b070ca9f6dca012c
=> Show the correct RA candidates for the virtual institution use case

docs/test-data.md, src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapIdentityCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapIdentityWithSmsSecondFactorCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapSmsSecondFactorCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/console_commands.yml
Creating identities is now handled with a separate command. This improves maintainability of the command significantly. Added bonus is that the class complexity is no longer unacceptable according to PHP MD.
https://www.pivotaltracker.com/story/show/172429585
=> Decouple identity creation

config/legacy/parameters.yaml.dist, config/packages/events.yaml, config/services.yaml, docs/personal-data.md, docs/postman/3.json, src/Surfnet/Stepup/Helper/SecondFactorProvePossessionHelper.php, src/Surfnet/Stepup/Identity/Api/Identity.php, src/Surfnet/Stepup/Identity/Entity/VerifiedSecondFactor.php, src/Surfnet/Stepup/Identity/Event/SecondFactorVettedWithoutTokenProofOfPossession.php, src/Surfnet/Stepup/Identity/Identity.php, src/Surfnet/Stepup/Tests/Identity/Event/ForgettableEventsTest.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/VerifiedSecondFactorController.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/AuditLogEntry.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaSecondFactorProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/SecondFactorProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/AuditLogRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/routing.yml, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Command/VetSecondFactorCommand.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/IdentityCommandHandler.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Processor/SecondFactorVettedEmailProcessor.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/command_handlers.yml, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/SecondFactorRevocationTest.php, src/Surfnet/StepupMiddleware/GatewayBundle/Projector/SecondFactorProjector.php
**Be aware that this is build on top of #307  so this needs to be merged back first!**
This change will effectively make the the prove possession step optional. It's possible to configure the second factors which do not require that step.
https://www.pivotaltracker.com/story/show/172911922
=> Make prove possession step optional

composer.lock, config/bundles.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapIdentityWithYubikeySecondFactorCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/EmailVerifiedSecondFactorRemindersCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/ReplayEventsCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/ReplaySpecificEventsCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/console_commands.yml, src/Surfnet/StepupMiddleware/MiddlewareBundle/SurfnetStepupMiddlewareMiddlewareBundle.php, symfony.lock
The console commands pulled out the container form its parent. This is highly discouraged, and only works for public services. To limit the amount of public services in the container, DI was implemented in the incriminating command.
In the end, all MW console commands have been migrated to use DI.
=> Implement depencency injection on console commands

src/Surfnet/Migrations/Version20160719090052.php
The migration is not removed from the project as the 'migration play head' would be corrupted. Instead a message is printed and a comment is added instructing users struck by the loss of this migration on how to deal with this problem.
See https://www.pivotaltracker.com/story/show/174702937
=> Remove migration logic from Version20160719090052

composer.json
I'm not shure why '*' was excluded, but it caused the new component_info was missing in the archive, and deploy failing.
=> Fix files not added to root of archive

config/legacy/parameters.yaml.dist, src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Service/AuthorizationContextService.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaCandidateController.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/AuthorizationRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaCandidateRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/RaCandidateService.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Service/AuthorizationContextServiceTest.php
Bugfix for the fact that the select RAA authorisation was not evaluated in the authorization context.
For a good bug report see: https://www.pivotaltracker.com/story/show/175056146
This touched Use-case C. I fixed the behat test for that scenario:
=> Allow authorization filtering on Select RAA

.gitignore, .travis.yml, config/legacy/bundles.yaml, config/legacy/parameters.yaml.dist, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/SecondFactorRevocationMailService.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/processors.yml, src/Surfnet/StepupMiddleware/MiddlewareBundle/DependencyInjection/Configuration.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/services.yml, src/Surfnet/StepupMiddleware/MiddlewareBundle/Service/SecondFactorDisplayNameResolverService.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Tests/Service/SecondFactorDisplayNameResolverServiceTest.php
In some templates/emails the internal/technical name of the second
factor is used. This adds a human readable displayname for the second
factor. If the name does not exists it will fallback to the internal
name.
See also: https://github.com/OpenConext/Stepup-Deploy/pull/124
https://www.pivotaltracker.com/story/show/174985988
=> Add a human readable display name for tokens

src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/AbstractBootstrapCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapGsspSecondFactorCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapSmsSecondFactorCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapYubikeySecondFactorCommand.php
Input validation was added for the registration status. This prevents strange behaviour in the execution of the command when a wrong argument is passed.
This was implemented for the three SF bootstrap commands
https://www.pivotaltracker.com/story/show/172429585
=> Add input validation for registration-status argument

src/Surfnet/Stepup/Identity/Event/SecondFactorVettedEvent.php, src/Surfnet/Stepup/Identity/Event/SecondFactorVettedWithoutTokenProofOfPossession.php, src/Surfnet/Stepup/Identity/Value/VettingTypeFactory.php, src/Surfnet/Stepup/Tests/Identity/Event/EventSerializationAndDeserializationTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/SensitiveData/SensitiveData.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/SensitiveData/SensitiveDataTest.php
There was a fix to prevent the vetting_type from going into the normal
event stream. However the vetting_type sensitive data was now being
deserialized back into the event because this logic wasn't yet moved
to the SensitiveData implementation in that fix.
=> Allow vetting_type sensitive data deserialization

src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapIdentityWithYubikeySecondFactorCommand.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/console_commands.yml
The other bootstrap commands already created the anonymous token. But
the identity + yubikeybootstrap combo command did not do this.
This commit fixes that.
=> Create anonymous token on bootstrap command

config/legacy/parameters.yaml.dist, config/packages/doctrine.yaml
Merged a bit to quickly, I addressed two review points from @pmeulen 
Part one can be found here, including the feedback mentioned above here #335
=>  Improve type safety by setting sql_mode to be strict part 2

composer.json
symfony/flex contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "symfony/flex" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?]
Newer versions of composer will throw the warning above.
=> Prevent composer warning

config/legacy/parameters.yaml.dist, src/Surfnet/Stepup/Identity/EventSourcing/IdentityRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/DeprovisionController.php, src/Surfnet/StepupMiddleware/ApiBundle/Exception/UserNotFoundException.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaListingProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaListingRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml, src/Surfnet/StepupMiddleware/ApiBundle/Service/DeprovisionService.php, src/Surfnet/StepupMiddleware/ApiBundle/Service/DeprovisionServiceInterface.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Service/DeprovisionServiceTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Command/DeprovisionExecutable.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Command/ForgetIdentityCommand.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Pipeline/AuthorizingStage.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/event_sourcing.yml, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerMoveTokenTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/RegistrationAuthorityCommandHandlerTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/RightToBeForgottenCommandHandlerTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/SecondFactorRevocationTest.php
In order to further automate the GDPR rules, it's beneficial to connect StepUp to the OpenConext UserLifecycle application. This automates the removal of inactive users from the platform. And allows for a practical way to retrieve all user data from the StepUp platform. And also allows for exercising the right to be forgotten.
To achieve this goal, I added a deprovision/userlifecycle endpoint to the Middleware API.
This API exposes two endpoints. One to retrieve data, and one to remove user data.
Data retrieval is done in a very practical manner. The events that are stored for the identiy that needs/wants to remove its data is collected from the event store. This data contains all relevant data for the user. Including sensitive data. That data is then serialized to JSON data and returned …
=> Implement deprovision methods

composer.lock, symfony.lock
Aiming to be up to date within our package version restraints, and also to remedy the security warning that was bugging us the previous PR's
Amongst the updates is Symfony Flex. It was upgraded from 1.13 to v1.18. I looked into upgrading to Flex 2, but the PHP 8 constrained stopped me from applying that change. @tvdijen this should help you out right? Judging from your comment on #337.
=> Install Composer updates

src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/SecondFactorStatusType.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/AuditLogProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/IdentityProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaSecondFactorProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/AuditLogRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaSecondFactorRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Value/SecondFactorStatus.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/SecondFactorStatusTypeTest.php
First of all: the data is anonymized, all sensitive data is still removed!
The data that was previously removed from the projections is now kept for the RaSecondFactor projection, the identity projection and the Audit Log projection. This only to allow RA's to see deprovisioned data in the second factor overview.
https://www.pivotaltracker.com/story/show/181172862
=> Do not remove the deprovisioned Identity data from the projections 

src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/routing.yml
The UserLifecyle script sends a DELETE http request with its deprovision
dry run. This was not yet supported by Middleware. We expected that to be
a regulare user-information GET request.
=> Update routing config to allow DELETE on dry-run

src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Service/CommandAuthorizationService.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/AuthorizationRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Service/CommandAuthorizationServiceTest.php
When vetting a token, the authorization check was not sharp enough. (incomplete)
1. The actor user's institution was only used to test for which other institutions it is allowed to perform tasks for. This would work for any configuration where 'regular' use-ra(a) configuration where set for that institution. When the RA is selected for a different institution, that test would not get the authorizations for that institution but just grab those of the 'home institution' of the actor. Adding a second query to also include the 'select_raa' authorizations for that institution fixed this problem.
2. To debug and get a grasp of what is happening in the Autz service. Quite some logging was added. The Autz repo also was exteded with some additional logging.
See …
=> Repair broken authz in mayRaCommandBeExecutedOnBehalfOf

src/Surfnet/Stepup/Helper/RecoveryTokenSecretHelper.php, src/Surfnet/Stepup/Identity/Event/SafeStoreSecretRecoveryTokenPossessionPromisedEvent.php, src/Surfnet/Stepup/Identity/Value/ForgottenSecret.php, src/Surfnet/Stepup/Identity/Value/HashableSecret.php, src/Surfnet/Stepup/Identity/Value/HashedSecret.php, src/Surfnet/Stepup/Identity/Value/RecoveryTokenIdentifierFactory.php, src/Surfnet/Stepup/Identity/Value/SafeStore.php, src/Surfnet/Stepup/Identity/Value/Secret.php, src/Surfnet/Stepup/Identity/Value/UnhashedSecret.php, src/Surfnet/Stepup/Tests/Identity/Value/RecoveryTokenIdentifierFactoryTest.php, src/Surfnet/Stepup/Tests/Identity/Value/SafeStoreTest.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/IdentityCommandHandler.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/command_handlers.yml, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerMoveTokenTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerSelfAssertedTokensTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/SecondFactorRevocationTest.php
As promised in #356, the actual hashing of the safe-store secret is now implemented.
See the three commit messages for greater detail on the context of this PR
This concludes task 4 of https://www.pivotaltracker.com/story/show/181934073
And see: https://www.pivotaltracker.com/story/show/181934021 for the design decisions regarding the hashing algorithm setup
=> Hash the safe-store secret

docs/MiddlewareAPI.md, docs/postman/3.json, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RecoveryTokenController.php, src/Surfnet/StepupMiddleware/ApiBundle/Exception/NotFoundException.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/RecoveryTokenQuery.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RecoveryTokenRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/RecoveryTokenService.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/routing.yml
A singular retrieve and search endpoint was added to the API. A new
controller was created that bundles the Recovery Token logic.
See Task 7 of https://www.pivotaltracker.com/story/show/181934073
=> Create read endpoints for Recovery Tokens

src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Service/CommandAuthorizationServiceTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Command/RegisterSelfAssertedSecondFactorCommand.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/IdentityCommandHandler.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerSelfAssertedTokensTest.php
A typo had snuck into the RegisterSelfAsser~edt~tedSecondFactorCommand
=> Rename typo in RegisterSelfAsseredtSecondFactorCommand

docs/MiddlewareAPI.md, docs/MiddlewareAPICommands.md, docs/postman/3.json, src/Surfnet/Migrations/Version20220628091800.php, src/Surfnet/Stepup/Identity/Value/VettingTypeFactory.php, src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Service/AuthorizationService.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/AuthorizationController.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/Identity.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/IdentitySelfAssertedTokenOptions.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/IdentityProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/IdentitySelfAssertedTokenOptionsProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/IdentitySelfAssertedTokenOptionsRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/IdentityService.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/projection.yml, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/routing.yml, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Service/AuthorizationServiceTest.php
The identity is only allowed to register a self-asserted token (SAT) when the Identity never owned a token. Or previously owned a self-asserted token.
To check this:
1. The Identity projection was updated, a new column was added projecting that property
2. The identity projector now applies the second factor vetted events, and checks if the token is of type SAT 
3. Finally the authorization endpoint now also evaluates this
As we are not able to replay the event stream on production environment, I suggest a database migration script is created that performs the check that is found in the projection before enabling the SAT feature. As all Identities that have a token prior to enabling this feature should have the `possessed_self_asserted_token` column set to `0`. Where the default value …
=> Upgrade self-asserted tokens allowed authorization check

src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/Identity.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/IdentityProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Response/JsonAuthorizationResponse.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Service/AuthorizationServiceTest.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Response/JsonAuthorizationResponseTest.php
Semantically from an HTTP protocol an authorization decision that denies a certain action should still result in a 200 response code. The authorization code embedded in the response body is still set to 403.
=> Return HTTP 200 when Authz is denied

src/Surfnet/Migrations/Version20220704084758.php, src/Surfnet/Migrations/Version20220704101721.php, src/Surfnet/Stepup/Identity/Entity/VerifiedSecondFactor.php, src/Surfnet/Stepup/Identity/Entity/VettedSecondFactor.php, src/Surfnet/Stepup/Identity/Event/SecondFactorMigratedEvent.php, src/Surfnet/Stepup/Identity/Identity.php, src/Surfnet/Stepup/Identity/Value/UnknownVettingType.php, src/Surfnet/Stepup/Identity/Value/VettingType.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/VettedSecondFactor.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/SecondFactorProjector.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerMoveTokenTest.php, src/Surfnet/StepupMiddleware/GatewayBundle/Entity/SecondFactor.php, src/Surfnet/StepupMiddleware/GatewayBundle/Projector/SecondFactorProjector.php
The vetting type is set on both the Gateway and Middleware Second Factor projections (for vetted second factors)
The vetting type is a relevant projection as it is used to determine the registration level of assurance (loa) of a second factor token.
=> Vetting type on vetted second factor projections

config/packages/doctrine.yaml, docs/MiddlewareAPI.md, src/Surfnet/Migrations/Version20220711125952.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/RecoveryTokenController.php, src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/RecoveryTokenStatusType.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/RecoveryToken.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RecoveryTokenProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/RecoveryTokenQuery.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RecoveryTokenRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/RecoveryTokenService.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Value/RecoveryTokenStatus.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/RecoveryTokenStatusTypeTest.php
Some features where missing to achieve this most notable are:
1. Several data was missing in the recovery tokens projection. For example we need the identity name, email, and institution in  order to inform the RA on which specific Identity owns the RT.
2. The RT DTO did not return the IdentityId
3. Searching RT's was very limited. Several query parameters where added (see docs for new options)
See: https://www.pivotaltracker.com/story/show/181934078
See: https://www.pivotaltracker.com/story/show/181968091
=> Support recovery token interactions in RA

src/Surfnet/Migrations/Version20220713123209.php, src/Surfnet/Stepup/Identity/Event/PhoneRecoveryTokenPossessionProvenEvent.php, src/Surfnet/Stepup/Identity/Event/SafeStoreSecretRecoveryTokenPossessionPromisedEvent.php, src/Surfnet/Stepup/Identity/Value/HiddenSecret.php, src/Surfnet/Stepup/Identity/Value/SafeStore.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/AuditLogEntry.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/AuditLogProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RecoveryTokenProjector.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/AuditLogRepository.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RecoveryTokenRepository.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/SensitiveData/SensitiveData.php
Two new columns are added in the audit log projection
The entity, repository and projections have been updated accordingly.
The events added the RT data to their audit log supply methods.
See: https://www.pivotaltracker.com/story/show/181934078
By accident, this PR also contains an update to support deprovisioning of recovery tokens
See: https://www.pivotaltracker.com/story/show/182168991
=> Add Recovery token events to audit log

src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Service/AuthorizationService.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/RecoveryTokenService.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Service/AuthorizationServiceTest.php
If a user looses both their activated token and their recovery method they cannot activate a token themselves. Allowing this would enable an attack whereby the attacker with only the first factor can delete and then add a new token to the account, upgrading it to a 2FA account. So getting out of this situation must involve an external verification step.
To do this, the user has to follow the normal service desk vetting process. I.e. register a token and then select the service desk activation method. The result is that the user will then have a normal loa2 or loa3 token. This is a higher level than the user had before, but this will work just fine. Using this process enables us to implement this scenario using the existing Stepup functionality.
The check missing in the existing authz …
=> Deny SAT when both RT and SAT SF are lost

.env, .github/workflows/test-integration.yml, composer.json, composer.lock, config/bundles.php, config/packages/dev/mailer.yaml, config/packages/dev/swiftmailer.yaml, config/packages/dev_event_replay/swiftmailer.yaml, config/packages/prod_event_replay/swiftmailer.yaml, config/packages/smoketest/swiftmailer.yaml, config/packages/smoketest_event_replay/swiftmailer.yaml, config/packages/swiftmailer.yaml, config/packages/test/mailer.yaml, config/packages/test/swiftmailer.yaml, src/Surfnet/StepupMiddleware/CommandHandlingBundle/DependencyInjection/SurfnetStepupMiddlewareCommandHandlingExtension.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/EmailVerificationMailService.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/RecoveryTokenMailService.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/RegistrationMailService.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/SecondFactorRevocationMailService.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/SecondFactorVettedMailService.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/processors.yml, src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/services.yml, src/Surfnet/StepupMiddleware/MiddlewareBundle/Service/VerifiedSecondFactorReminderMailService.php, symfony.lock
All mail services that used the deprecated Swiftmailer are not using Symfony mailer.
https://www.pivotaltracker.com/story/show/179976844
=> Replace deprecated Swiftmailer with Symfony mailer

src/Surfnet/StepupMiddleware/ApiBundle/Service/DeprovisionService.php, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Service/DeprovisionServiceTest.php
Previously we returned a failed response when an identity is not found
in Middleware. This behavior changes as per [1]. We now return an
OK-with-an-empty-array response.
1: https://www.pivotaltracker.com/n/projects/1163646/stories/182988799
=> Respond with OK when identity not found

src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/RecoveryTokenMailService.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/RegistrationMailService.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/SecondFactorRevocationMailService.php, src/Surfnet/StepupMiddleware/MiddlewareBundle/Service/VerifiedSecondFactorReminderMailService.php
The to and from methods of the `TemplatedEmail` ask for addresses as its parameter. They are resolved quite magically. Setting a string with a plain mail address is possible, adding multiple parameters is cool too.
The issue we ran into was that the addres param was followed by a common name string. Both where resoved as being mail addresses. Causing the application to blow up on the common name. The solution is to provide Address objects. An address consists of an address and a name.
See: https://www.pivotaltracker.com/n/projects/1163646/stories/183362518
See: https://symfony.com/doc/4.4/mailer.html#email-addresses
=> Wrap address and name into an Address

src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/processors.yml, src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/services.yml
Some of our Composer dependencies still rely on Swiftmailer. And hence we have the mailer in the di container. On my previous (not to thorough, ahem) review I did not notice this discrepency. And the mailers would keep working as the interface change between the Swift_mailer and the SF Mailer is not changed on the methods we use.
Except for the ones where we passed the (email, name) construction without wrapping them in an Address (see previous PR#377).
Quite the pickle!
See: #377
See: https://www.pivotaltracker.com/n/projects/1163646/stories/183362518
=> Refrain from injecting old Swift_Mailer

composer.lock, config/bundles.php, config/packages/dev/swiftmailer.yaml, config/packages/swiftmailer.yaml, config/packages/test/mailer.yaml, config/packages/test/swiftmailer.yaml
They cause the application to try and load the Swiftmailer bundle. This was placed on the original PR, but was never reworked. And in the end, I just hit the merge button..
(╯°□°)╯︵ ┻━┻
I merged the old config with the new mailer config settings as good as possible. The one change required was to disable delivery in the test env. This was achieved by setting the DSN to null://null. As suggested in: https://symfony.com/doc/4.4/mailer.html#disabling-delivery
See: #352 #377 #378
=> Remove old swiftmailer config files

src/Surfnet/StepupMiddleware/ApiBundle/Controller/DeprovisionController.php
When a user can not be deprovision (e.g. it was already forgotten) the deprovision endpoint no longer returns a FAILED response, but just responds OK with an empty data array.
See https://www.pivotaltracker.com/story/show/183312425
=> Make deprovision less strict

docs/MiddlewareConfiguration.md, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/RecoveryTokenMailService.php
The MiddlewareConfiguration allows setting mail templates. These templates have several purposes. Each of these are described in the MiddlewareConfiguration.md.
The new Recovery Token related mail templates where not yet represented in this readme.
In addition to documenting them. Some additional parameters have been made available. To align them more with the Second Factor counterparts.
=> Update documentation for recovery token API config

src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/RecoveryTokenMailService.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Processor/RecoveryTokenEmailProcessor.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/processors.yml, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Processor/RecoveryTokenEmailProcessorTest.php
These events result in a mail message being sent. Note that I decided to merge the sending of the revocation and the creation messages in the very same processor. I have renamed the processor to reflect that change of responsibility more clearly.
=> Listen for recovery token possession events

CHANGELOG.md, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/SecondFactorProjector.php
Backport from https://github.com/OpenConext/Stepup-Middleware/commit/326cb0717297123c3be3f5eddb0c5188e44d66f0 
A missing `use Surfnet\Stepup\Identity\Event\SecondFactorMigratedEvent` causes an error during the middleware:migrate:vetted-tokens console command
=> Fix token migration TypeError due to missing use statement

src/Surfnet/Migrations/Version20220519134637.php, src/Surfnet/StepupMiddleware/GatewayBundle/Entity/SecondFactor.php
The final 4.5 release already added the second_factor.vetting_type column (later renamed to: `identity_vetted`). Adding it here is not possible. 
The Migration name (timestamp) was updated to be next in sequence to the 4.5 migration.
See task 3 of: https://www.pivotaltracker.com/story/show/184191063
=> Update SAT projection

src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaCandidateRepository.php
You require a LoA 3 with a vetted idenity token in order to be a RA(A) candidate. The Middelware would later verify this action in the Identity aggregate. But showing only available options in the RA application is good practice. So the filtereing logic to find the available RA candidates was adjusted slightly.
See: https://www.pivotaltracker.com/story/show/184306171
=> Filter non identity-vetted RA candidates

composer.lock, config/legacy/bundles.yaml, config/legacy/parameters.yaml.dist, docs/MiddlewareAPI.md, docs/postman/3.json, src/Surfnet/Stepup/Identity/Api/Identity.php, src/Surfnet/Stepup/Identity/Entity/RecoveryTokenCollection.php, src/Surfnet/Stepup/Identity/Entity/VerifiedSecondFactor.php, src/Surfnet/Stepup/Identity/Identity.php, src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Service/AuthorizationService.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/AuthorizationController.php, src/Surfnet/StepupMiddleware/ApiBundle/Controller/CommandController.php, src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/routing.yml, src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Service/AuthorizationServiceTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Command/AbstractCommand.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Command/SelfVetSecondFactorCommand.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/IdentityCommandHandler.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerSelfAssertedTokensTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php, src/Surfnet/StepupMiddleware/GatewayBundle/Projector/SecondFactorProjector.php, symfony.lock
When an Identity is in possession of a vetted self-asserted token. It should be allowed to self-vet successive tokens using that SAT. But only when all tokens are of the SAT type. Once an Identity is in possession of an idenity vetted token (vetted on-premise), all following self vetting tokens must be done with the identity vetted token.
For details see: https://www.pivotaltracker.com/story/show/184292087
And: https://github.com/OpenConext/Stepup-SelfService/pull/284
=> Support self-vetting of self-asserted tokens

src/Surfnet/StepupMiddleware/GatewayBundle/Projector/InstitutionConfigurationProjector.php, src/Surfnet/StepupMiddleware/GatewayBundle/Tests/Projector/InstitutionConfigurationProjectorTest.php
When the Gateway institution configuration is updated because the sso on 2fa config changed for that institution. The projection would only be updated if the institution already exists in the projection. If the projection did not yet have the institution, then the projection was not updated.
This fix now creates the row if the projection is not yet present. This only works now that we only track one single configuration value. 
Note that the real solution to this problem would be to do an event replay. But to prevent an event replay on `prod` we choose to add this construction.
https://www.pivotaltracker.com/story/show/185833305
=> Create Gateway Institution Configuration projection row if not exists

.github/workflows/build-push-docker-image.yml, .github/workflows/tag-release.yml, config/legacy/parameters.yaml.dist, config/packages/prod/monolog.yaml.docker, docker/Dockerfile.prod, docker/conf/middleware-apache2.conf
This PR is part of the larger project where we aim to build docker containers of all Stepup apps. All the application .dist files are modified so they will, when instantiated, out of the box with the other docker containers (with a docker-compose file that can be found here: https://github.com/OpenConext/OpenConext-devconf/blob/main/stepup/docker-compose.yml
=> Docker: Create a parameters.yaml.dist that works in a docker dev env

src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/RegistrationMailService.php
The expiration dates displayed in selfservice web UI and the corresponding email you receive are not the same:
This PR changes that by making the algoritms the same (without endOfDay()) so they will be consistent. Further improvement of timezone handling is thinkable but in any case the algoritms should be the same.
=> Make mail expiration date match selfservice

ci/qa/phpstan-baseline.neon, src/Surfnet/Stepup/Identity/Api/Identity.php, src/Surfnet/Stepup/Identity/Event/IdentityRestoredEvent.php, src/Surfnet/Stepup/Identity/Event/SafeStoreSecretRecoveryTokenPossessionPromisedEvent.php, src/Surfnet/Stepup/Identity/Identity.php, src/Surfnet/Stepup/Identity/Value/SafeStore.php, src/Surfnet/Stepup/Tests/Identity/Event/EventSerializationAndDeserializationTest.php, src/Surfnet/Stepup/Tests/Identity/Event/ForgettableEventsTest.php, src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/IdentityProjector.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/IdentityCommandHandler.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php
Earlier on it was not possible to restore identities after
they were forgotten. Now logic is added to restore and reset
the identity email, name and tokens in the identity aggregate
so the identity is reset.
https://github.com/OpenConext/Stepup-Middleware/issues/525
=> Allow identity restoration

ci/qa/phpstan-baseline.neon, src/Surfnet/Stepup/Identity/Identity.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerMoveTokenTest.php, src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerUniqueTypeRegistrationTest.php
We add a check to prevent the same token having multiple in flight registration processes for the same token.
https://github.com/OpenConext/Stepup-Gateway/issues/462
https://github.com/OpenConext/Stepup-SelfService/issues/463
=> Check already registered on prove possession
