OpenConext/Stepup-Middleware

- src/Surfnet/StepupMiddleware/ApiBundle/EventListener/ExceptionListener.php
> Let ExceptionListener ignore HttpExceptions

- src/Surfnet/StepupMiddleware/ApiBundle/EventListener/ExceptionListener.php
> Make JSON responses out of HttpExceptions (incl. headers)

- build-pre-commit.xml
- composer.json
- composer.lock
- src/Surfnet/Stepup/Configuration/EventSourcing/ConfigurationRepository.php
- src/Surfnet/Stepup/Identity/EventSourcing/IdentityRepository.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/EventHandling/BufferedEventBus.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/event_sourcing.yml
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php
> Upgrade broadway

- src/Surfnet/Stepup/Identity/Api/Identity.php
- src/Surfnet/Stepup/Identity/Event/GssfPossessionProvenEvent.php
- src/Surfnet/Stepup/Identity/Identity.php
- src/Surfnet/Stepup/Identity/Value/GssfId.php
- src/Surfnet/Stepup/Identity/Value/Institution.php
- src/Surfnet/Stepup/Identity/Value/StepupProvider.php
- src/Surfnet/Stepup/Tests/Identity/Event/EventSerializationAndDeserializationTest.php
- src/Surfnet/Stepup/Tests/Identity/Value/GssfIdTest.php
- src/Surfnet/Stepup/Tests/Identity/Value/InstitutionTest.php
- src/Surfnet/Stepup/Tests/Identity/Value/StepupProviderTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/SecondFactorProjector.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Command/ProveGssfPossessionCommand.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/IdentityCommandHandler.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php
> Saml Second Factor Handling

- composer.json
- composer.lock
- src/Surfnet/Stepup/Identity/Value/PhoneNumber.php
- src/Surfnet/Stepup/Tests/Identity/Event/EventSerializationAndDeserializationTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Command/ProvePhonePossessionCommand.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php
Depends on https://github.com/SURFnet/Stepup-bundle/pull/12
> Change required format of PhoneNumber to fit new requirements

- app/config/config_dev_event_replay.yml
- app/config/config_prod_event_replay.yml
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/EventHandling/BufferedEventBus.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Exception/AlreadyFlushingException.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Exception/LogicException.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/EventHandling/BufferedEventBusTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/EventHandling/OnFirstCallPublishesToBusAndCountingCallsEventListener.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/ReplayEventsCommand.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/DependencyInjection/SurfnetStepupMiddlewareMiddlewareExtension.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/EventSourcing/DBALEventHydrator.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Exception/UnknownDBALConnectionException.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/event_replaying.yml
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/services.yml
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Service/DBALConnectionHelper.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Service/EventStreamReplayer.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/SurfnetStepupMiddlewareMiddlewareBundle.php
Depends on https://github.com/SURFnet/Stepup-Middleware/pull/60
> Adding command to replay events

- src/Surfnet/Stepup/Identity/Api/Identity.php
- src/Surfnet/Stepup/Identity/Entity/RegistrationAuthority.php
- src/Surfnet/Stepup/Identity/Event/RegistrationAuthorityInformationAmendedEvent.php
- src/Surfnet/Stepup/Identity/Identity.php
- src/Surfnet/Stepup/Tests/Identity/Event/EventSerializationAndDeserializationTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaListingController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaListingProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaaProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaListingRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/RaListingService.php
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/routing.yml
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Command/AmendRegistrationAuthorityInformationCommand.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/RegistrationAuthorityCommandHandler.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/RegistrationAuthorityCommandHandlerTest.php
> Allow a registration authority's information to be amended

- src/Surfnet/StepupMiddleware/ApiBundle/Controller/CommandController.php
depends on https://github.com/SURFnet/Stepup-Middleware-clientbundle/pull/32
> Fix the check for institution for UpdateIdentityCommand

- app/DoctrineMigrations/Version20150617141129.php
- app/DoctrineMigrations/Version20150618121907.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/SecondFactorRevocation.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/SecondFactorRevocationProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/SecondFactorRevocationRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/projection.yml
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Service/EventStreamReplayer.php
> Project vetted second factor revocations

- composer.json
- composer.lock
- src/Surfnet/Stepup/Identity/Value/YubikeyPublicId.php
- src/Surfnet/Stepup/Tests/Identity/Event/EventSerializationAndDeserializationTest.php
- src/Surfnet/Stepup/Tests/Identity/Value/SecondFactorIdentifierFactoryTest.php
- src/Surfnet/Stepup/Tests/Identity/Value/YubikeyPublicIdTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/RegistrationAuthorityCommandHandlerTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/RightToBeForgottenCommandHandlerTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/SecondFactorRevocationTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/SensitiveData/SensitiveDataTest.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Service/EventStreamReplayer.php
> Switch to numerical Yubikey public IDs

- app/Resources/translations/messages.en_GB.xliff
- app/Resources/translations/messages.nl_NL.xliff
- src/Surfnet/Stepup/Identity/Value/Locale.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Processor/EmailProcessor.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/SecondFactorMailService.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_configuration/invalid_email_template_locale.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_configuration/missing_email_template_locale.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Validator/EmailTemplatesConfigurationValidator.php
> Send e-mail to registrant when token is vetted

- README.md
Migrated https://wiki.surfnet.nl/display/stepup/Middleware+Configuration
> Migrate confluence docs to README.

- app/DoctrineMigrations/Version20160607142244.php
- app/config/config.yml
- src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/DocumentNumberType.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/RaSecondFactor.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaSecondFactorProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/DocumentNumberTypeTest.php
https://www.pivotaltracker.com/n/projects/1163646/stories/113612625
> Add document number to RA SF projection

- src/Surfnet/Stepup/Configuration/Api/InstitutionConfiguration.php
- src/Surfnet/Stepup/Configuration/Entity/RaLocation.php
- src/Surfnet/Stepup/Configuration/Event/InstitutionConfigurationCreatedEvent.php
- src/Surfnet/Stepup/Configuration/Event/NewInstitutionConfigurationCreatedEvent.php
- src/Surfnet/Stepup/Configuration/Event/RaLocationAddedEvent.php
- src/Surfnet/Stepup/Configuration/Event/RaLocationContactInformationChangedEvent.php
- src/Surfnet/Stepup/Configuration/Event/RaLocationRelocatedEvent.php
- src/Surfnet/Stepup/Configuration/Event/RaLocationRemovedEvent.php
- src/Surfnet/Stepup/Configuration/Event/RaLocationRenamedEvent.php
- src/Surfnet/Stepup/Configuration/InstitutionConfiguration.php
- src/Surfnet/Stepup/Configuration/Value/ContactInformation.php
- src/Surfnet/Stepup/Configuration/Value/Institution.php
- src/Surfnet/Stepup/Configuration/Value/InstitutionConfigurationId.php
- src/Surfnet/Stepup/Configuration/Value/Location.php
- src/Surfnet/Stepup/Configuration/Value/RaLocationId.php
- src/Surfnet/Stepup/Configuration/Value/RaLocationList.php
- src/Surfnet/Stepup/Configuration/Value/RaLocationName.php
- src/Surfnet/Stepup/Identity/Value/ContactInformation.php
- src/Surfnet/Stepup/Identity/Value/Location.php
- src/Surfnet/Stepup/Tests/Configuration/Event/EventSerializationAndDeserializationTest.php
- src/Surfnet/Stepup/Tests/Configuration/InstitutionConfigurationTest.php
- src/Surfnet/Stepup/Tests/Configuration/Value/ContactInformationTest.php
- src/Surfnet/Stepup/Tests/Configuration/Value/InstitutionConfigurationIdTest.php
- src/Surfnet/Stepup/Tests/Configuration/Value/LocationTest.php
- src/Surfnet/Stepup/Tests/Configuration/Value/RaLocationIdTest.php
- src/Surfnet/Stepup/Tests/Configuration/Value/RaLocationListTest.php
- src/Surfnet/Stepup/Tests/Configuration/Value/RaLocationNameTest.php
Part of [#116602125](https://www.pivotaltracker.com/story/show/116602125).
This PR is meant to get the model right before moving on to each separate Event, Command and the handling thereof.
> RA Locations: establishing the model

- app/config/config.yml
- app/config/config_dev_event_replay.yml
- app/config/config_prod_event_replay.yml
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/DependencyInjection/Configuration.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/DependencyInjection/SurfnetStepupMiddlewareCommandHandlingExtension.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/SecondFactorMailService.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/processors.yml
- src/Surfnet/StepupMiddleware/ManagementBundle/Configuration/Repository/EmailTemplateRepository.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Configuration/Service/EmailTemplateService.php
Fixes event replaying for missing document numbers.
> Warn on missing email template

- app/DoctrineMigrations/Version20160617153313.php
- app/DoctrineMigrations/Version20160617163830.php
- app/config/config.yml
- src/Surfnet/Stepup/Configuration/Value/ContactInformation.php
- src/Surfnet/Stepup/Configuration/Value/Institution.php
- src/Surfnet/Stepup/Configuration/Value/InstitutionConfigurationId.php
- src/Surfnet/Stepup/Configuration/Value/Location.php
- src/Surfnet/Stepup/Configuration/Value/RaLocationId.php
- src/Surfnet/Stepup/Configuration/Value/RaLocationName.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Entity/RaLocation.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Projector/RaLocationProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Query/RaLocationQuery.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Repository/RaLocationRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Service/RaLocationService.php
- src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/ConfigurationContactInformationType.php
- src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/ConfigurationInstitutionType.php
- src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/ConfigurationLocationType.php
- src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/DocumentNumberType.php
- src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/RaLocationNameType.php
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/projection.yml
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml
- src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/ConfigurationContactInformationTypeTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/ConfigurationInstitutionTypeTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/ConfigurationLocationTypeTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/DocumentNumberTypeTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/InstitutionTypeTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Tests/Doctrine/Type/RaLocationNameTypeTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Tests/TestDataProvider.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/MigrationsDiffDoctrineCommand.php
[116602125](https://www.pivotaltracker.com/story/show/116602125)
> Add RA location projections

- app/DoctrineMigrations/Version20160620153812.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Entity/RaLocation.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Query/RaLocationQuery.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Repository/RaLocationRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Service/RaLocationService.php
- src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaLocationController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Request/ConfigurationInstitutionParamConverter.php
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/routing.yml
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml
[116602125](https://www.pivotaltracker.com/story/show/116602125)
> Add controller and route for RA location

- app/DoctrineMigrations/Version20160620153812.php
See title. 
General tip: pull develop often, run migrations when needed.
> Correct faulty migration as a column has been removed since diffing

- src/Surfnet/Stepup/Tests/Configuration/Value/LocationTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/projection.yml
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/Processor/InstitutionConfigurationProcessor.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/DependencyInjection/CompilerPass/AddEventBusListenersCompilerPass.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Service/SecondFactorMailService.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/processors.yml
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Configuration/Processor/InstitutionConfigurationProcessorTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Mockery/HasInstitutionMatcher.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Mockery/HasInstitutionMatcherTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Mockery/TestObjects/ObjectWithInstitutionAccessor.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Mockery/TestObjects/ObjectWithInstitutionProperty.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Mockery/TestObjects/ObjectWithoutInstitutionPropertyAndAccessor.php
- src/Surfnet/StepupMiddleware/GatewayBundle/Resources/config/projection.yml
- src/Surfnet/StepupMiddleware/ManagementBundle/Resources/config/services.yml
This also contains a bugfix for the `InstitutionConfigurationProcessor` and a bit of clean-up.
> Specify event listeners for replaying

- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Processor/EmailProcessor.php
This should be tested more extensively.
> If showRaaContactInformation is false, RAAs should not be shown

- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/AuditLogRepository.php
[133246727](https://www.pivotaltracker.com/story/show/133246727)
This adds the missing fields to order the audit log by.
SURFnet/Stepup-RA#130
> Add properties to order audit log by

- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/Command/RemoveInstitutionConfigurationByUnnormalizedIdCommand.php
https://www.pivotaltracker.com/story/show/135610963
> Introduction of RemoveInstitutionConfigurationByUnnormalizedIdCommand

- src/Surfnet/Stepup/Configuration/Api/InstitutionConfiguration.php
- src/Surfnet/Stepup/Configuration/Event/InstitutionConfigurationRemovedEvent.php
- src/Surfnet/Stepup/Configuration/InstitutionConfiguration.php
- src/Surfnet/Stepup/Tests/Configuration/Event/EventSerializationAndDeserializationTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Projector/ConfiguredInstitutionProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Projector/InstitutionConfigurationOptionsProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Projector/RaLocationProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Repository/ConfiguredInstitutionRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Repository/InstitutionConfigurationOptionsRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Repository/RaLocationRepository.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/Command/RemoveInstitutionConfigurationByUnnormalizedIdCommand.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/CommandHandler/InstitutionConfigurationCommandHandler.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Configuration/CommandHandler/InstitutionConfigurationCommandHandlerTest.php
https://www.pivotaltracker.com/story/show/135610963
Based on #164
> Process institution configuration removal

- src/Surfnet/Stepup/Configuration/Api/InstitutionConfiguration.php
- src/Surfnet/Stepup/Configuration/Event/InstitutionConfigurationRemovedEvent.php
- src/Surfnet/Stepup/Configuration/InstitutionConfiguration.php
- src/Surfnet/Stepup/Configuration/Value/ShowRaaContactInformationOption.php
- src/Surfnet/Stepup/Configuration/Value/UseRaLocationsOption.php
- src/Surfnet/Stepup/Tests/Configuration/Value/ShowRaaContactInformationOptionTest.php
- src/Surfnet/Stepup/Tests/Configuration/Value/UseRaLocationsOptionTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Projector/ConfiguredInstitutionProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Projector/InstitutionConfigurationOptionsProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Projector/RaLocationProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Repository/ConfiguredInstitutionRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Repository/InstitutionConfigurationOptionsRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Repository/RaLocationRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Service/RaLocationService.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/Command/RemoveInstitutionConfigurationByUnnormalizedIdCommand.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/CommandHandler/InstitutionConfigurationCommandHandler.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Configuration/CommandHandler/InstitutionConfigurationCommandHandlerTest.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Exception/RuntimeException.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Migrations/InstitutionConfiguration/InstitutionConfigurationProvider.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Migrations/InstitutionConfiguration/InstitutionConfigurationState.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Migrations/InstitutionConfiguration/MappedInstitutionConfiguration.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Tests/Migrations/InstitutionConfiguration/MappedInstitutionConfigurationTest.php
https://www.pivotaltracker.com/story/show/135610963
Based on #165
> Add Command generation for Institution Configuration Migration

- README.md
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/Command/RemoveInstitutionConfigurationByUnnormalizedIdCommand.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/MigrateInstitutionConfigurationsCommand.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/services.yml
- src/Surfnet/StepupMiddleware/MiddlewareBundle/SurfnetStepupMiddlewareMiddlewareBundle.php
[135610963](https://www.pivotaltracker.com/story/show/135610963)
The phrasing probably needs some work. Suggestions welcome.
> Document that institutions are dealt with case-insensitively in configuration

- README.md
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/missing_allowed_second_factors_option.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/missing_show_raa_contact_information_option.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/missing_use_ra_locations_option.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/not_array_allowed_second_factors_option.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/not_boolean_show_raa_contact_information_option.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/not_strings_allowed_second_factors_option.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/not_valid_second_factor_types_allowed_second_factors_option.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/with_error_in_second_institution.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/with_extra_options.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/ReconfigureInstitutionRequestValidatorTest.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Validator/ReconfigureInstitutionRequestValidator.php
> Update reconfigure command in Management API

- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/Command/ReconfigureInstitutionConfigurationOptionsCommand.php
> Add allowedSecondFactors to reconfigure institution configuration command

- src/Surfnet/Stepup/Configuration/Event/AllowedSecondFactorListUpdatedEvent.php
- src/Surfnet/Stepup/Configuration/Value/AllowedSecondFactorList.php
- src/Surfnet/Stepup/Tests/Configuration/Event/EventSerializationAndDeserializationTest.php
> Introduce AllowedSecondFactorListUpdatedEvent

- src/Surfnet/Stepup/Configuration/InstitutionConfiguration.php
- src/Surfnet/Stepup/Configuration/Value/AllowedSecondFactorList.php
- src/Surfnet/Stepup/Tests/Configuration/InstitutionConfigurationTest.php
- src/Surfnet/Stepup/Tests/Configuration/Value/AllowedSecondFactorListTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/Command/ReconfigureInstitutionConfigurationOptionsCommand.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/CommandHandler/InstitutionConfigurationCommandHandler.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Configuration/CommandHandler/InstitutionConfigurationCommandHandlerTest.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Controller/InstitutionConfigurationController.php
Branched from #174
Update: rebased on develop.
> Update institution configuration aggregate, command handling, API

- app/DoctrineMigrations/Version20170210140051.php
- app/config/config.yml
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Entity/AllowedSecondFactor.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Projector/AllowedSecondFactorListProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Projector/InstitutionConfigurationOptionsProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Repository/AllowedSecondFactorRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/SecondFactorTypeType.php
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/projection.yml
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml
> Allowed second factor projections

- src/Surfnet/Stepup/Configuration/InstitutionConfiguration.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Projector/AllowedSecondFactorListProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Service/AllowedSecondFactorListService.php
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/projection.yml
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/routing.yml
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/EventListener/CommandProcessingExceptionListener.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/EventListener/ProcessingAbortedExceptionListener.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Exception/SecondFactorNotAllowedException.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/IdentityCommandHandler.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/command_handlers.yml
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/pipeline.yml
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/SecondFactorRevocationTest.php
> Enforce Allowed Second Factor List

- app/config/config.yml
- app/config/events.yml
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/ReplaySpecificEventsCommand.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/EventSourcing/EventCollection.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/SurfnetStepupMiddlewareMiddlewareBundle.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Tests/EventSourcing/EventCollectionTest.php
> Introduce event collection and events.yml

- src/Surfnet/StepupMiddleware/MiddlewareBundle/DependencyInjection/CompilerPass/CollectProjectorsForEventReplayCompilerPass.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/EventSourcing/ProjectorCollection.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/event_replaying.yml
- src/Surfnet/StepupMiddleware/MiddlewareBundle/SurfnetStepupMiddlewareMiddlewareBundle.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Tests/EventSourcing/ProjectorCollectionTest.php
> Introduce ProjectorCollection and collecting projectors by tags

- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/ReplaySpecificEventsCommand.php
> Add projection overview to ReplaySpecificEventsCommand

- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/ReplaySpecificEventsCommand.php
> Add event overview to ReplaySpecificEventsCommand

- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/ReplaySpecificEventsCommand.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/EventSourcing/EventCollection.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/EventSourcing/ProjectorCollection.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Tests/EventSourcing/EventCollectionTest.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Tests/EventSourcing/ProjectorCollectionTest.php
> Add projector selection to ReplaySpecificEventsCommand 

- README.md
> Document adding events

- src/Surfnet/Stepup/Tests/Identity/Event/EventSerializationAndDeserializationTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/IdentityRepository.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/Exception/DuplicateIdentityException.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/IdentityCommandHandler.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Resources/config/command_handlers.yml
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/DateTimeHelperTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/SecondFactorRevocationTest.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapIdentityWithYubikeySecondFactorCommand.php
https://www.pivotaltracker.com/story/show/103002156
> Prevent bootstrapping of an existing identity

- src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaCandidateController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/RaCandidateQuery.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaCandidateRepository.php
Allow to filter on second factor types, in order to request a list of RA candidates with a specific LoA.
https://www.pivotaltracker.com/story/show/131617617
> Filter second factor types

- docs/MiddlewareAPI.md
- docs/postman/3.json
- src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaSecondFactorController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/RaSecondFactorService.php
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/routing.yml
By adding a new api endpoint on the Middleware API.
> Facilitate RA token export

- README.md
- app/config/config_dev.yml
- app/config/config_test.yml
- app/config/parameters.yml.dist
- composer.json
- composer.lock
Based on Pieters work in the dev-vm branch, but added some additional commits.
> Change dev logging configuration to use syslog instead of graylog

- src/Surfnet/Stepup/Identity/Identity.php
- src/Surfnet/Stepup/Tests/Identity/Entity/SecondFactorCollectionTest.php
See [pivotal](https://www.pivotaltracker.com/story/show/157687939).
> Better handling and logging of authority without vetted second factors edge-case

- .travis.yml
- CHANGELOG.md
- app/DoctrineMigrations/Version20180918120046.php
- app/config/config.yml
- docs/MiddlewareConfiguration.md
- docs/postman/2.json
- src/Surfnet/Stepup/Configuration/InstitutionConfiguration.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Entity/InstitutionConfigurationOptions.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Projector/InstitutionConfigurationOptionsProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/SelectRaaOptionType.php
- src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/UseRaOptionType.php
- src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/UseRaaOptionType.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Controller/InstitutionConfigurationController.php
**What's new?**
This PR is built on top of #232 before merging, make sure that other PR is approved. And rebase any changes onto this branch.
1. The institution configuration options projection is updated, the FGA options are now part of that projection. 
2. The aggregate was updated once again, as nulling the FGA options did not work correctly yet.
3. A new migration was added to this PR that stores the FGA options on the Institution configuration options entity. This is a first place to store this information. A new entity might be introduced that will be dedicated to the FGA options and make them easily retrievable if the need arises.
**What's left to do?**
See the tasks on the ticket for more info on this topic.
**How to test?**
See #232
See …
> Update projections for the FGA settings

- .travis.yml
- docs/MiddlewareAPI.md
- src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Service/InstitutionAuthorizationContextFactory.php
- src/Surfnet/StepupMiddleware/ApiBundle/Authorization/Service/InstitutionAuthorizationContextFactoryInterface.php
- src/Surfnet/StepupMiddleware/ApiBundle/Controller/IdentityController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/AuthorizationAwareQuery.php
- src/Surfnet/StepupMiddleware/ApiBundle/Tests/Authorization/Service/InstitutionAuthorizationContextFactoryTest.php
This PR takes care of the first two tasks described in this [story](https://www.pivotaltracker.com/story/show/160983081).
> Add authorization context to IdentityQuery

- src/Surfnet/StepupMiddleware/ApiBundle/Controller/InstitutionConfigurationOptionsController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaSecondFactorController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/RaSecondFactorQuery.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaSecondFactorRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Request/ActorInstitutionParamConverter.php
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/services.yml
- src/Surfnet/StepupMiddleware/ApiBundle/Tests/Request/ActorInstitutionParamConverterTest.php
Add support for filtering on institutions.
This PR is part of: 
* https://github.com/OpenConext/Stepup-RA/pull/169 for the RA changes
* https://github.com/OpenConext/Stepup-SelfService/pull/158 for the SelfService change.
* https://github.com/OpenConext/Stepup-Middleware-clientbundle/pull/59
> Allow filtering on institutions when searching second factor tokens

- docs/MiddlewareAPI.md
- src/Surfnet/StepupMiddleware/ApiBundle/Controller/VerifiedSecondFactorController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/VerifiedSecondFactorQuery.php
Extends the work of #243, see that PR for more details.
> Allow filtering on institutions when searching second factor tokens II

- docs/MiddlewareAPI.md
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/AuditLogRepository.php
And update the MiddlewareAPI.md accordingly.
> Allow sorting on actorInstitution

- CHANGELOG.md
- app/DoctrineMigrations/Version20181023151546.php
- docs/MiddlewareAPI.md
- src/Surfnet/Stepup/Identity/Api/Identity.php
- src/Surfnet/Stepup/Identity/Event/AppointedAsRaForInstitutionEvent.php
- src/Surfnet/Stepup/Identity/Event/AppointedAsRaaForInstitutionEvent.php
- src/Surfnet/Stepup/Identity/Event/AppointedInstitutionAsRaEvent.php
- src/Surfnet/Stepup/Identity/Event/IdentityAccreditedAsRaForInstitutionEvent.php
- src/Surfnet/Stepup/Identity/Event/IdentityAccreditedAsRaaForInstitutionEvent.php
- src/Surfnet/Stepup/Identity/Event/RegistrationAuthorityInformationAmendedForInstitutionEvent.php
- src/Surfnet/Stepup/Identity/Event/RegistrationAuthorityRetractedForInstitutionEvent.php
- src/Surfnet/Stepup/Identity/Identity.php
- src/Surfnet/Stepup/Tests/Configuration/Value/InstitutionAuthorizationOptionTest.php
- src/Surfnet/Stepup/Tests/Identity/Event/EventSerializationAndDeserializationTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Controller/VerifiedSecondFactorController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaCandidateProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaListingProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/VerifiedSecondFactorQuery.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/AuditLogRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaCandidateRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaListingRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Tests/Identity/Projector/RaCandidateProjectorTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Command/AccreditIdentityCommand.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/CommandHandler/RegistrationAuthorityCommandHandler.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/RegistrationAuthorityCommandHandlerTest.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/RightToBeForgottenCommandHandlerTest.php
Add RAA managment to middleware to allow the registration of RAA from another institution.
> Add RAA management to Middleware

- docs/MiddlewareAPI.md
- src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaListingController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/RaListingQuery.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaListingRepository.php
@pablothedude please carefully review 26e1898 specifically
> Allow filtering on identityId for ra listing

- build.xml
- composer.json
- composer.lock
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaCandidateProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaCandidateRepository.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Configuration/CommandHandler/InstitutionConfigurationCommandHandler.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Identity/Command/ProveGssfPossessionCommand.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Validator/ReconfigureInstitutionRequestValidator.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Service/EventStreamReplayer.php
See: https://www.pivotaltracker.com/story/show/163226922
> Perform security related chores

- docs/MiddlewareAPI.md
- docs/postman/3.json
- src/Surfnet/StepupMiddleware/ApiBundle/Controller/ProfileController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaListingRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/IdentityService.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/ProfileService.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/RaListingService.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Value/AuthorizedInstitutionCollection.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Value/Profile.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Value/RegistrationAuthorityCredentials.php
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/routing.yml
- src/Surfnet/StepupMiddleware/ApiBundle/Tests/Identity/Value/AuthorizedInstitutionCollectionTest.php
> Create a profile endpoint

- app/DoctrineMigrations/Version20190211163604.php
- src/Surfnet/StepupMiddleware/ApiBundle/Configuration/Entity/InstitutionAuthorization.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/AuditLogEntry.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/RaCandidate.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/RaListing.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Entity/VerifiedSecondFactor.php
This will add indices to work with the fga changes.
https://www.pivotaltracker.com/story/show/161310060
> Update indices for FGA changes

- docs/MiddlewareAPI.md
- src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaListingController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/RaListingQuery.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaListingRepository.php
We now allow searching the ra listing with more filtering options than
before. This to allow the RA overview to be filtered.
https://www.pivotaltracker.com/story/show/163903559
https://github.com/OpenConext/Stepup-Middleware-clientbundle/pull/78
> Allow searching on name, email and role

- src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaCandidateController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaListingController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Controller/RaSecondFactorController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/InstitutionListingRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaCandidateRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaListingRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Repository/RaSecondFactorRepository.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/RaCandidateService.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/RaListingService.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Service/RaSecondFactorService.php
- src/Surfnet/StepupMiddleware/ApiBundle/Response/JsonCollectionResponse.php
In order to use the filters on the ra-second-factors ra-listing and
ra-candidate page we need to return the possible available filters.
> Add filter options to pagination results

- CHANGELOG.md
- composer.lock
Symfony was upgraded to 3.4.26
Twig was upgraded to 1.39.1
> Install security upgrades

- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Query/RaListingQuery.php
Inherit pageing size from the base class
https://www.pivotaltracker.com/story/show/163859942
> Enable paging for RA Management

- composer.lock
Update Symfony to 3.4.36 and Twig to 1.42.2
> Security upgrades

- docs/test-data.md
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapGsspSecondFactorCommand.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapSmsSecondFactorCommand.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/console_commands.yml
Bootstrap a GSSP token
Other than the Yubikey and SMS token, an additional token type argument was added to the command.
Please, first review and merge #304 as this PR was based on that.
https://www.pivotaltracker.com/story/show/172429585
> Bootstrap gssp command

- docs/test-data.md
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/AbstractBootstrapCommand.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapGsspSecondFactorCommand.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapIdentityWithYubikeySecondFactorCommand.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapSmsSecondFactorCommand.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Console/Command/BootstrapYubikeySecondFactorCommand.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Resources/config/console_commands.yml
This PR adds the possibility to bootstrap a Yubikey token
In the process a method was moved to the abstract command. This was also trickled down to the SMS bootstrap command.
https://www.pivotaltracker.com/story/show/172429585
> Bootstrap yubikey command

- .gitignore
- build.xml
- composer.json
- composer.lock
Local PHP security checker was implemented by:
1. Adding the download and run actions to the composer.json
2. Running them via ANT for interoperability. (Hope we move away from ant in the near future!)
3. Added .gitignore entry and cleaned up some more crud there. :deciduous_tree: Boy Scout Rule
> Update security checker

- docs/personal-data.md
- src/Surfnet/Stepup/Identity/Event/AppointedAsRaForInstitutionEvent.php
- src/Surfnet/Stepup/Identity/Event/AppointedAsRaaForInstitutionEvent.php
- src/Surfnet/Stepup/Identity/Event/CompliedWithRevocationEvent.php
- src/Surfnet/Stepup/Identity/Event/EmailVerifiedEvent.php
- src/Surfnet/Stepup/Identity/Event/GssfPossessionProvenAndVerifiedEvent.php
- src/Surfnet/Stepup/Identity/Event/GssfPossessionProvenEvent.php
- src/Surfnet/Stepup/Identity/Event/IdentityAccreditedAsRaForInstitutionEvent.php
- src/Surfnet/Stepup/Identity/Event/IdentityAccreditedAsRaaForInstitutionEvent.php
- src/Surfnet/Stepup/Identity/Event/IdentityCreatedEvent.php
- src/Surfnet/Stepup/Identity/Event/IdentityEmailChangedEvent.php
- src/Surfnet/Stepup/Identity/Event/IdentityForgottenEvent.php
- src/Surfnet/Stepup/Identity/Event/IdentityRenamedEvent.php
- src/Surfnet/Stepup/Identity/Event/InstitutionsAddedToWhitelistEvent.php
- src/Surfnet/Stepup/Identity/Event/InstitutionsRemovedFromWhitelistEvent.php
- src/Surfnet/Stepup/Identity/Event/LocalePreferenceExpressedEvent.php
- src/Surfnet/Stepup/Identity/Event/PhonePossessionProvenAndVerifiedEvent.php
- src/Surfnet/Stepup/Identity/Event/PhonePossessionProvenEvent.php
- src/Surfnet/Stepup/Identity/Event/RegistrationAuthorityRetractedForInstitutionEvent.php
- src/Surfnet/Stepup/Identity/Event/SecondFactorRevokedEvent.php
- src/Surfnet/Stepup/Identity/Event/SecondFactorVettedEvent.php
- src/Surfnet/Stepup/Identity/Event/SecondFactorVettedWithoutTokenProofOfPossession.php
- src/Surfnet/Stepup/Identity/Event/U2fDevicePossessionProvenAndVerifiedEvent.php
- src/Surfnet/Stepup/Identity/Event/U2fDevicePossessionProvenEvent.php
- src/Surfnet/Stepup/Identity/Event/VettedSecondFactorsAllRevokedEvent.php
- src/Surfnet/Stepup/Identity/Event/WhitelistCreatedEvent.php
- src/Surfnet/Stepup/Identity/Event/WhitelistReplacedEvent.php
- src/Surfnet/Stepup/Identity/Event/YubikeyPossessionProvenAndVerifiedEvent.php
- src/Surfnet/Stepup/Identity/Event/YubikeyPossessionProvenEvent.php
- src/Surfnet/Stepup/Identity/Event/YubikeySecondFactorBootstrappedEvent.php
The details can be found here: https://www.pivotaltracker.com/story/show/178390934
> Remove vetting type from event stream

- src/Surfnet/Migrations/Version20210610131957.php
A prepared statement should be used to prevent incorrect escaping in
the resulting serialized payload when running the vetting_type
migration.
> Prepared statement for vetting_type migration

- docs/MiddlewareAPI.md
I'm not sure why it would be, but it is.
> docs: identity endpoint requires institution

- config/packages/events.yaml
- docs/personal-data.md
- src/Surfnet/Stepup/Identity/Api/Identity.php
- src/Surfnet/Stepup/Identity/Event/U2fDevicePossessionProvenAndVerifiedEvent.php
- src/Surfnet/Stepup/Identity/Event/U2fDevicePossessionProvenEvent.php
- src/Surfnet/Stepup/Identity/Identity.php
- src/Surfnet/Stepup/Identity/Value/SecondFactorIdentifierFactory.php
- src/Surfnet/Stepup/Identity/Value/U2fKeyHandle.php
- src/Surfnet/Stepup/Tests/Identity/Event/ForgettableEventsTest.php
- src/Surfnet/Stepup/Tests/Identity/Value/SecondFactorIdentifierFactoryTest.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/RaSecondFactorProjector.php
- src/Surfnet/StepupMiddleware/ApiBundle/Identity/Projector/SecondFactorProjector.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Processor/EmailVerificationEmailProcessor.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Processor/RegistrationEmailProcessor.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php
https://www.pivotaltracker.com/story/show/168109427
> Drop support for u2f

- config/legacy/parameters.yaml.dist
- config/packages/security.yaml
- docs/MiddlewareAPI.md
- docs/postman/3.json
- src/Surfnet/StepupMiddleware/ApiBundle/Controller/DeprovisionController.php
- src/Surfnet/StepupMiddleware/ApiBundle/Resources/config/routing.yml
Creates:
- The deprovision user
- Deprovision controller with two actions (deprovision and dry run)
- Router configuration for the aforementioned actions
- Updated API docs
- Two deprovision calls in the Postman collection
> Add a deprovision endpoint

- composer.json
- composer.lock
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Processor/RecoveryTokenRevocationEmailProcessor.php
- src/Surfnet/StepupMiddleware/CommandHandlingBundle/Tests/Identity/CommandHandler/IdentityCommandHandlerTest.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Migrations/InstitutionConfiguration/InstitutionConfigurationState.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Migrations/InstitutionConfiguration/MappedInstitutionConfiguration.php
- src/Surfnet/StepupMiddleware/MiddlewareBundle/Service/VerifiedSecondFactorReminderMailService.php
- symfony.lock
First commit closes https://github.com/OpenConext/Stepup-SelfService/issues/273
The others are bonus
> Bugfix: add missing parameters

- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/missing_allow_self_asserted_tokens_option.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/missing_allowed_second_factors_option.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/missing_self_vet_option.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/missing_show_raa_contact_information_option.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/missing_use_ra_locations_option.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/with_error_in_second_institution.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Tests/Validator/Fixtures/invalid_reconfigure_institution_request/with_extra_options.php
- src/Surfnet/StepupMiddleware/ManagementBundle/Validator/ReconfigureInstitutionRequestValidator.php
As discussed in https://www.pivotaltracker.com/n/projects/1163646/stories/181933607/comments/234093784
> Fix misleading institution configuration error message

- docs/MiddlewareConfiguration.md
- src/Surfnet/StepupMiddleware/ManagementBundle/Validator/ServiceProviderConfigurationValidator.php
These options are optional and are defaulted to false.
See: https://www.pivotaltracker.com/story/show/183511012
> Add optional config parameters to MW SP config

- CHANGELOG.md
- composer.lock
- src/Surfnet/Migrations/Version20220519134637.php
This column value represents the vetting type of the vetted second factors. Any SF vetted before this change are marked as vetting type 'unknown'.
Consumers of this column (the RA and SS apps) will have to make an informed decision on how to translate the unknown vetting type.
See: https://www.pivotaltracker.com/story/show/184191063
> Set default value for vetted_second_factor vetting_type column

- docs/MiddlewareConfiguration.md
- src/Surfnet/Migrations/Version20250501121457.php
- src/Surfnet/Stepup/Configuration/Event/NewInstitutionConfigurationCreatedEvent.php
- src/Surfnet/Stepup/Configuration/Event/SsoRegistrationBypassOptionChangedEvent.php
- src/Surfnet/Stepup/Configuration/Value/SsoRegistrationBypassOption.php
- src/Surfnet/StepupMiddleware/ApiBundle/Doctrine/Type/SsoRegistrationBypassOptionType.php
- src/Surfnet/StepupMiddleware/GatewayBundle/Entity/InstitutionConfiguration.php
Add comments in the code to link the name of the feature to the internally used "sso registration bypass" for this feature.
See: https://github.com/OpenConext/Stepup-Project/issues/628
> Document the GSSP Fallback feature
